name: CI-CD
on: push
jobs:
    Create-upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Create a text file
              run: echo "Hello world....!" > hello.txt

            - name: Upload the text file
              uses: actions/upload-artifact@v4
              with: 
                name: hello-txt-file
                path: hello.txt

    Download-test:
        needs: Create-upload
        runs-on: ubuntu-latest
        steps:
            - name: Download the txt file
              uses: actions/download-artifact@v4
              with:
                name: hello-txt-file

            - name: read and display that text file
              run: cat hello.txt

        
        

